// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIrY44o-UHiwEvbwMkOxQW_GrjPgCCuLo',
    appId: '1:15618668600:web:a6f71e63870f2d51b50ecd',
    messagingSenderId: '15618668600',
    projectId: 'instaagram-13251',
    authDomain: 'instaagram-13251.firebaseapp.com',
    storageBucket: 'instaagram-13251.appspot.com',
    measurementId: 'G-G1WWEZD213',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1HcrnrR3AwllAXSWE-Q9S_jVGitb4q_Q',
    appId: '1:15618668600:android:7302bc3ac4d46bf9b50ecd',
    messagingSenderId: '15618668600',
    projectId: 'instaagram-13251',
    storageBucket: 'instaagram-13251.appspot.com',
  );
}
